defaults:
  - _self_
  - dataset: null # /dataset/data; /dataset/result
  - prompt: null
  - model: null
  - setup: null

root: /Users/Rodion.Khvorostov/Desktop/Prog/Other/deck_generator
data_dir: ${root}/data

secrets: ${root}/conf/secret.json
